### ISSUE TITLE
post processor fails with Unexpected EOF if any Launch Template in the account does not have an AMI ImageId

### ISSUE THREAD

**Issue by bminahan-kc** [wata727/packer-post-processor-amazon-ami-management#124]
in cleaner.go it will iterate through every launch template in the account and every launch template version. From there if one of the old launch template versions does not have an associated imageId (i.e someone deregisters the image), the post processor will throw an Unexpected EOF.

The workaround is to delete the now invalid launch template version(s) and rerun. This is problematic because maybe the launch templates causing the issue may not your responsibility / may be completely unrelated to the packer builder.

To resolve the issue cleaner.go would need to catch this error (null imageId)  and continue iterating over the launch templates. Since the ImageId is null it is safe to do so since obviously it does not match the imageId to be deleted.

Here is an example log for when this happens:

```2020/10/14 18:29:49 packer-post-processor-amazon-ami-management plugin: 2020/10/14 18:29:49 [INFO] (aws): No AWS timeout and polling overrides have been set. Packer will default to waiter-specific delays and timeouts. If you would like to customize the length of time between retries and max number of retries you may do so by setting the environment variables AWS_POLL_DELAY_SECONDS and AWS_MAX_ATTEMPTS to your desired values.
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: panic: runtime error: invalid memory address or nil pointer dereference
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11399f0]
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin:
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: goroutine 24 [running]:
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: main.(*Cleaner).setLaunchTemplateUsed(0xc000308000, 0x0, 0x0)
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin:         /home/runner/work/packer-post-processor-amazon-ami-management/packer-post-processor-amazon-ami-management/cleaner.go:220 +0x200
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: main.NewCleaner(0xc00000a3c0, 0xc000574650, 0xe, 0xc000574690, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin:         /home/runner/work/packer-post-processor-amazon-ami-management/packer-post-processor-amazon-ami-management/cleaner.go:62 +0x213
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: main.(*PostProcessor).PostProcess(0xc000304800, 0x18ba4c0, 0xc0001cc800, 0x18c0a20, 0xc00058abd0, 0x18c0a80, 0xc00056bc00, 0x7f34d472e640, 0x203000, 0xaa, ...)
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin:         /home/runner/work/packer-post-processor-amazon-ami-management/packer-post-processor-amazon-ami-management/post-processor.go:80 +0x737
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: github.com/hashicorp/packer/packer/rpc.(*PostProcessorServer).PostProcess(0xc0001cd700, 0x1, 0xc000030020, 0x0, 0x0)
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin:         /home/runner/go/pkg/mod/github.com/hashicorp/packer@v1.5.4/packer/rpc/post_processor.go:109 +0x277
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: reflect.Value.call(0xc00007bc80, 0xc00000eb48, 0x13, 0x15cd42d, 0x4, 0xc00008ef18, 0x3, 0x3, 0xc0004b9e78, 0x40541c, ...)
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin:         /opt/hostedtoolcache/go/1.13.8/x64/src/reflect/value.go:460 +0x5f6
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: reflect.Value.Call(0xc00007bc80, 0xc00000eb48, 0x13, 0xc0004b9f18, 0x3, 0x3, 0xc0004085a0, 0xc0003f9200, 0xc0003f9288)
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin:         /opt/hostedtoolcache/go/1.13.8/x64/src/reflect/value.go:321 +0xb4
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: net/rpc.(*service).call(0xc0001cd740, 0xc00009f400, 0xc000374868, 0xc000374870, 0xc0000e4a00, 0xc0003077c0, 0x125c4c0, 0xc0000380f0, 0x18a, 0x12092e0, ...)
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin:         /opt/hostedtoolcache/go/1.13.8/x64/src/net/rpc/server.go:377 +0x16f
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin: created by net/rpc.(*Server).ServeCodec
2020/10/14 18:29:50 packer-post-processor-amazon-ami-management plugin:         /opt/hostedtoolcache/go/1.13.8/x64/src/net/rpc/server.go:474 +0x42b
2020/10/14 18:29:50 [INFO] (telemetry) ending amazon-ami-management
2020/10/14 18:29:50 Deleting original artifact for build 'amazon-ebs.ami-management'
2020/10/14 18:29:50 /home/ec2-user/.packer.d/plugins/packer-post-processor-amazon-ami-management: plugin process exited
2020/10/14 18:29:50 packer-builder-amazon-ebs plugin: Deregistering image ID (ami-XXXX) from region (REGION)
2020/10/14 18:29:50 packer-builder-amazon-ebs plugin: Deregistered AMI id: ami-XXXX
2020/10/14 18:29:50 packer-builder-amazon-ebs plugin: Deleted snapshot: snap-XXXX
2020/10/14 18:29:50 packer-builder-amazon-ebs plugin: Deleted snapshot: snap-XXXX
2020/10/14 18:29:50 ui error: Build 'amazon-ebs.ami-management' errored: 1 error(s) occurred:```

**Comment by bminahan-kc** [comment]
thanks for the work you do @wata727 ! this plugin has been really useful to us.
