### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kondanta** [wata727/packer-post-processor-amazon-ami-management#60]
Hi!
I am getting below error when I try to use this plugin on `eu-central-1`. I also have parallel bake operations where I create exact copy of the same AMI in different locations. This problem only occurs on `eu-central-1`. Rest of the regions are working perfectly fine. 

Here's the error log: 
```
panic: runtime error: invalid memory address or nil pointer dereference
108 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1001cb7]
109 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: 
110 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: goroutine 93 [running]:
111 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: main.(*Cleaner).setLaunchTemplateUsed(0xc0004da000, 0x0, 0x0)
112 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/wata727/packer-post-processor-amazon-ami-management/cleaner.go:220 +0x207
113 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: main.NewCleaner(0xc0004d41c0, 0xc00048c160, 0x13, 0xc000438280, 0xa, 0x100, 0x0, 0x0, 0xc0004856e0, 0x0, ...)
114 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/wata727/packer-post-processor-amazon-ami-management/cleaner.go:62 +0x221
115 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: main.(*PostProcessor).PostProcess(0xc0003e4000, 0x163bcc0, 0xc000304a00, 0x1641780, 0xc0003090a0, 0x16417e0, 0xc0003090c0, 0xc00009eb78, 0xc0003f6020, 0x2, ...)
116 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/src/github.com/wata727/packer-post-processor-amazon-ami-management/post-processor.go:88 +0x753
117 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: github.com/hashicorp/packer/packer/rpc.(*PostProcessorServer).PostProcess(0xc00030b470, 0x1, 0xc0004993e0, 0x0, 0x0)
118 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: 	/Users/watanabekazuma/workspace/golang/pkg/mod/github.com/hashicorp/packer@v1.4.1/packer/rpc/post_processor.go:107 +0x243
119 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: reflect.Value.call(0xc00030ea80, 0xc000340148, 0x13, 0x140198a, 0x4, 0xc00009ef18, 0x3, 0x3, 0xc000328fc0, 0x120a220, ...)
120 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: 	/usr/local/Cellar/go/1.12.7/libexec/src/reflect/value.go:447 +0x461
121 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: reflect.Value.Call(0xc00030ea80, 0xc000340148, 0x13, 0xc0004aaf18, 0x3, 0x3, 0xc00030e960, 0xc0004aaec0, 0x2)
122 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: 	/usr/local/Cellar/go/1.12.7/libexec/src/reflect/value.go:308 +0xa4
123 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: net/rpc.(*service).call(0xc000304980, 0xc00034c3c0, 0xc00003fd30, 0xc00003fd40, 0xc000344900, 0xc0003f6040, 0x1107400, 0xc000438520, 0x18a, 0x10bc320, ...)
124 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: 	/usr/local/Cellar/go/1.12.7/libexec/src/net/rpc/server.go:384 +0x14e
125 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: created by net/rpc.(*Server).ServeCodec
126 2019/12/30 12:50:39 packer-post-processor-amazon-ami-management: 	/usr/local/Cellar/go/1.12.7/libexec/src/net/rpc/server.go:481 +0x42b
127 2019/12/30 12:50:39 [INFO] (telemetry) ending amazon-ami-management
128 2019/12/30 12:50:39 ui error: Build 'apibalancer builder' errored: 1 error(s) occurred:
129 * Post-processor failed: unexpected EOF
130 2019/12/30 12:50:39 machine readable: error-count []string{"1"}
131 2019/12/30 12:50:39 ui error: 
132 ==> Some builds didn't complete successfully and had errors:
133 2019/12/30 12:50:39 machine readable: apibalancer builder,error []string{"1 error(s) occurred:\n\n* Post-processor failed: unexpected EOF"}
134 2019/12/30 12:50:39 ui error: --> apibalancer builder: 1 error(s) occurred:
135 * Post-processor failed: unexpected EOF
136 2019/12/30 12:50:39 ui: 
137 ==> Builds finished but no artifacts were created.
138 2019/12/30 12:50:39 /home/gitlab-runner/.packer.d/plugins/packer-post-processor-amazon-ami-management: plugin process exited
139 2019/12/30 12:50:39 Cancelling post-processor after context cancellation context canceled
140 2019/12/30 12:50:39 Error cancelling post-processor: connection is shut down
141 2019/12/30 12:50:39 [INFO] (telemetry) Finalizing.
142 2019/12/30 12:50:39 waiting for all plugin processes to complete...
143 2019/12/30 12:50:39 /usr/local/bin/packer: plugin process exited
144 2019/12/30 12:50:39 /usr/local/bin/packer: plugin process exited
145 2019/12/30 12:50:39 /usr/local/bin/packer: plugin process exited
146 2019/12/30 12:50:39 /usr/local/bin/packer: plugin process exited
147 2019/12/30 12:50:39 /usr/local/bin/packer: plugin process exited
148 !!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
149 Packer crashed! This is always indicative of a bug within Packer.
150 A crash log has been placed at "crash.log" relative to your current
151 working directory. It would be immensely helpful if you could please
152 report the crash with Packer[1] so that we can fix this.
153 [1]: https://github.com/hashicorp/packer/issues
154 !!!!!!!!!!!!!!!!!!!!!!!!!!! PACKER CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
157
bash: line 82: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8): No such file or directory
00:00
158 bash: line 82: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
160 ERROR: Job failed: exit status 1
```

**Comment by kondanta** [comment]
I've realized that I have an empty launch template so that was the thing that causing this issue.

**Comment by fleaz** [comment]
Hey @kondanta ,

can you explain what you mean by "empty launch template"? Because I'm hitting the exact same error :D

**Comment by kondanta** [comment]
Hey @fleaz ,

In my case, there was a launch template that we forgot the delete. And of course it was broken. I was able to find it in `EC2 > Instances > Launch Templates` section. Consider checking them and be sure all of the launch templates are pointing existing AMIs. Deleting ones that does not have valid AMIs was fixed my issue.
